from http import HTTPStatus


STATUS = {
    'OK': HTTPStatus.OK,
    'CONFLICT': HTTPStatus.CONFLICT,
    'CREATED': HTTPStatus.CREATED,
    'ACCEPTED': HTTPStatus.ACCEPTED,
    'UNAUTHORIZED': HTTPStatus.UNAUTHORIZED,
    'FORBIDDEN': HTTPStatus.FORBIDDEN,
    'NOT_FOUND': HTTPStatus.NOT_FOUND,
}
